# ===============================
# APP NAME
# ===============================
spring.application.name=complaint-service

# ===============================
# DATABASE
# Uses environment variables in production
# Falls back to local values in development
# ===============================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/complaint_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# ML SERVICE URL
# ===============================
ml.service.url=${ML_SERVICE_URL:http://localhost:8000}

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:SmartComplaintSystemSecretKey2026VeryLongAndSecureKey}
jwt.expiration=86400000
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Memory optimization for Railway free tier
JAVA_TOOL_OPTIONS=-Xmx256m -Xms128m

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.tomcat.max-threads=20
server.tomcat.min-spare-threads=5