spring.application.name=complaint-service
# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/complaint_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===============================
# JPA / HIBERNATE SETTINGS
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# SERVER
# ===============================
server.port=8080
# ===============================
# JWT SECURITY
# ===============================
jwt.secret=SmartComplaintSystemSecretKey2026VeryLongAndSecureKey
jwt.expiration=86400000
# 86400000 ms = 24 hours
spring.security.user.name=disable
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
